### ISSUE TITLE
Define more standard tags in the future?

### ISSUE THREAD

**Issue by dominikh** [opentracing/opentracing.io#104]
The Data Semantics Guidelines define a handful of standard tags for HTTP and peer relations. Is it planned to add tags for things like database drivers, gRPC (or RPC in general) and other common kinds of libraries and services? Or do you plan to let the community, or individual software projects, define their own tags?

*_Edit_::
Here's a list of tags that came to mind while instrumenting code. I propose that others add their own tags here as well.
- [ ] `rpc.method` for an RPC method name

**Comment by yurishkuro** [comment]
@dominikh yes, there will be more standard tags in the future. The purpose of standard tags is to unify/standardize instrumentation and help tracing systems gain more insight into the data. If you have some std tags in mind, feel free to propose.

**Comment by yurishkuro** [comment]
PS. Having said that, it's currently a very manual task adding new tags in all languages, so we might punt on adding any more until we add some automation for them, per https://github.com/opentracing/opentracing.github.io/issues/76

**Comment by bensigelman** [comment]
... continued at https://github.com/opentracing/specification/issues/13.
