### ISSUE TITLE
Clarification of HTTP_HEADERS format requirements

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#113]
This is taken from Go implementation, but I believe I've seen similar inconsistencies in other implementations. In Go the definition of HTTP_HEADERs format says

```
        // Unlike TextMap, the HTTPHeaders format requires that the keys and values
    // be valid as HTTP headers as-is (i.e., character casing may be unstable
    // and special characters are disallowed in keys, values should be
    // URL-escaped, etc).
```

The way I interpret it is the Tracer is responsible for encoding / url-encoding keys/values before inserting them into the carrier. However, the `HTTPHeadersCarrier` helper class `[has this](https://github.com/opentracing/opentracing-go/blob/master/propagation.go#L148)`:

``` go
// Set conforms to the TextMapWriter interface.
func (c HTTPHeadersCarrier) Set(key, val string) {
    h := http.Header(c)
    h.Add(key, url.QueryEscape(val))
}
```

which would do an _additional_ url-encoding of the value.

IMO the spec is right, but the helper code is wrong in this case. The helper code should be simply `c.Add(key, value)`.

@bensigelman

**Comment by bensigelman** [comment]
@yurishkuro I agree about both the spec (being right) and the code (being wrong / not being updated when it should have been).

**Comment by yurishkuro** [comment]
One thing I am uncertain about is whether we can count on all http frameworks to respect the client's values. For example, Go's HTTPHeader certainly doesn't respect the case of the keys. Could it be that some frameworks have similar "helpful" abstractions over HTTP headers where they e.g. automatically url-encode values, whether you want it or not?  In those scenarios the tracer is going to have a hard time.

**Comment by bensigelman** [comment]
IMO the HTTP case is a mess, and the Tracer impls would do well to "play it safe", whatever that means.

**Comment by cwe1ss** [comment]
Shouldn't the implementing tracer handle the actual copying of baggage into the headers? Only it could know if it e.g wants to append a prefix (e.g. x-trace-*) or filter the entries, etc.
If I understand correctly, the API should only allow a user to tell the tracer which format should be used, but implementation is up to it, right?

**Comment by yurishkuro** [comment]
@cwe1ss Tracer does decide if it wants to append the prefix or not. The issue here is that the tracer may not be given access to the actual headers. It's given access to the "carrier", which could be directly passing data onto headers, or storing them and the instrumentation later transfers them from carrier to headers. So in the latter case, the instrumentation might apply additional url-encoding of the values (which is what was happening in `HTTPHeadersCarrier`), but it would be the wrong thing to do if we clarify that the Tracer is responsible for doing that.

**Comment by bensigelman** [comment]
... continued at https://github.com/opentracing/specification/issues/15
