### ISSUE TITLE
feature request: inter-trace references

### ISSUE THREAD

**Issue by RaduBerinde** [opentracing/opentracing.io#119]
Currently, the only way to associate two spans is to create a parent-child relationship via `ChildOf` or `FollowsFrom`.

Sometimes there is a need to make an association between traces for different operations that end up interacting in some way. Most importantly, this association needs to happen after creating the Spans (not simply as an argument to `StartSpan`).

The use case we have is around transactions. Each transaction has a trace. Sometimes transactions end up conflicting with each other, and there is a need to find the spans of a transaction A that is causing transaction B to stall. We need B's Span to somehow have a reference to A's span. There is no way to express such an association with the current API.

`StartSpan` allows (at least in `opentracing-go`) multiple references, so conceivably one could create a Span that `FollowsFrom` both txn A and txn B's spans. But this is a bit of a hack and I think it goes beyond the intention of the APIs, and doesn't work in practice because most implementations (e.g. `basictracer-go`) can't handle multiple parents.

**Comment by yurishkuro** [comment]
I think this is essentially the same issue as #28

**Comment by bensigelman** [comment]
(@yurishkuro agreed!)

**Comment by adriancole** [comment]
there's also this, as it has often been discussed as "linked traces" https://github.com/openzipkin/zipkin/issues/1244

**Comment by bensigelman** [comment]
... continued at https://github.com/opentracing/specification/issues/17
