### ISSUE TITLE
I'm translating opentracing.io Document to Simplified Chinese

### ISSUE THREAD

**Issue by wu-sheng** [opentracing/opentracing.io#149]
I am author of an open tracer project named [SkyWalking](https://github.com/wu-sheng/sky-walking). It's a very popular java tracer project in China.
And I am very intrested OpenTracing, and intend to alter my instrument in order to support OpenTracing.
By using OpenTracing, I find these is no Simplified Chinese version of opentracing.io website, so I decide to translate for chinese users.
So, I fork the project, create a branch [translation/chn/201611) ](https://github.com/wu-sheng/opentracing.io/tree/translation/chn/201611),  create a gitbook [opentracing.io在线文档中文版 ( 翻译 ) 吴晟](https://www.gitbook.com/book/wu-sheng/opentracing-io/details), have a [document website](https://wu-sheng.gitbooks.io/opentracing-io/content/).

In Order to more chinese users known the translation, I want to send a pull request to official opentracing.io project, or add a Simplified Chinese version link to my website, on the main page. 

Is this possible?
Looking forward your reply.

**Comment by bensigelman** [comment]
@wu-sheng: Thanks for being in touch, and this is a very generous offer!

This will be a hard thing to keep in sync. Do you know of other projects that have kept Simplified Chinese versions up-to-date? Should we instead focus on translating the most important documents and leaving it at that? (E.g., the main OpenTracing specification)

Separately, please let us know how we can help with the SkyWalking integration.

**Comment by wu-sheng** [comment]
@bensigelman , Thanks for your reply. First, I am not clear enough about translating optracing.io. I am agree with you, that focus on translating the most import documents. And that is I am doing now. As same as grpc.io documents, there is a Simplified Chinese version. This is will very helpful for Chinese users and OpenTracing Specification.  So many developers do not have enough English to read the document. 

Up-to date problem is not so important. Most Simplified Chinese version documents focus on the main version, which have  numerous changes.  Simplified Chinese version is helping the users to know what is OpecTracing.

This is online document: https://wu-sheng.gitbooks.io/opentracing-io/content/. Is this the most import documents as you mentioned? Should we keep two language version of documents on official document page? Let users to choose?

Separately. As SkyWalking’s author, I am going to integrate OpenTracing‘s java version on next month, after we release 2.0 version. If I am problems, I will let your known.

How should we have further communication? continue on this page? or should I send direct E-mail to you? 
My mail addr: wu.sheng@foxmail.com. if you send me the first mail, please let me known on the page. I am worried this mail addr is not working in same country. It works on github, but not work on twitter, strange things. Thanks for your understanding.

**Comment by wu-sheng** [comment]
@bensigelman , can you create a branch on opentracing/opentracing.io, and I rp my translation to the branch?

**Comment by wu-sheng** [comment]
Waiting for https://github.com/opentracing/specification/issues/2

**Comment by wu-sheng** [comment]
Oops, I forgot to close this. Translation works are done for now.
