### ISSUE TITLE
Create a CONTRIBUTING.md

### ISSUE THREAD

**Issue by reimertz** [opentracing/opentracing.io#150]
I suggest we migrate some of the contets related to contributing out of readme.md into a new file, focused on contributing. these are usually named CONTRIBUTING.md. 

This is a good reference: https://github.com/yarnpkg/yarn/blob/master/CONTRIBUTING.md

**Comment by wu-sheng** [comment]
I think these should be the default steps for any contributors in GitHub. Is this necessary？

**Comment by reimertz** [comment]
It is the default steps for people like you and me who have contributed and know the default steps, but if you don't, then you'll need this. :)

**Comment by wu-sheng** [comment]
LGTM.  @yurishkuro , @adriancole ?

**Comment by yurishkuro** [comment]
I think the link @reimertz posted is a good example. Another good one: https://github.com/uber/jaeger-client-go/blob/master/CONTRIBUTING.md

**Comment by wu-sheng** [comment]
@reimertz , I think `CONTRIBUTING.md` should stay in simple. This repository present as website and doc, not lib or system like other repositories.

**Comment by bensigelman** [comment]
(Sounds like a plan to me...)
