### ISSUE TITLE
What does "ad hoc HTTP calls" mean?

### ISSUE THREAD

**Issue by wu-sheng** [opentracing/opentracing.io#158]
In Section 1.4.3, in `"The Big Picture" for explicit trace propagation`, there is a cross-process called `ad hoc HTTP calls`.

HTTP calls is easy to understand, but what is **ad hoc**? I am confused.

@yurishkuro @bensigelman

**Comment by yurishkuro** [comment]
Probably not the best term. In this context it refers to making an http call using some low-level http library as opposed to using a full fledged RPC framework

**Comment by bensigelman** [comment]
^^^ what @yurishkuro said. Other terms (that aren't in Latin!) might be "one-off HTTP calls" or "manual HTTP calls".

**Comment by wu-sheng** [comment]
like using apache httpclient in java？

**Comment by bensigelman** [comment]
@wu-sheng yeah, I think the point is that you are making the HTTP calls directly rather than via a framework (like Thrift or GRPC) that happens to make HTTP calls on your behalf.

**Comment by wu-sheng** [comment]
where is 'ad hoc' from? which other language?
I am very curiousness.

**Comment by bensigelman** [comment]
@wu-sheng it's Latin, but used in English, at least by snobs like me :)

https://en.wikipedia.org/wiki/Ad_hoc

**Comment by wu-sheng** [comment]
I hope to chang it to*directly* or *low-level http calls*,  is OK？
I think it's easier to understand like me, who know little things about Latin.   :(

If look good to you, I will pr it.

**Comment by bensigelman** [comment]
@wu-sheng I've just made the change for you (directly in master, no PR). Thanks for pointing it out.

**Comment by wu-sheng** [comment]
thank you
