### ISSUE TITLE
get/set_baggage_item not expected on SpanContext

### ISSUE THREAD

**Issue by mabn** [opentracing/opentracing.io#161]
[The spec](http://opentracing.io/documentation/pages/spec.html) says:

> The SpanContext interface must have the following capabilities.
> (...)
> Set a Baggage item (...)
> Get a Baggage item by key. (py: get_baggage_item, go: BaggageItem)

But https://github.com/opentracing/opentracing.io/issues/106 moved these methods to Span.

**Comment by yurishkuro** [comment]
The spec is outdated, has not been updated to reflect #106

**Comment by wu-sheng** [comment]
@yurishkuro @bensigelman , should we add a version and updated log to the opentracing.io doc?

I have mentioned before in #153. I think it will be very helpful for readers, translators and anyone using the spec.

**Comment by yurishkuro** [comment]
Problem is we haven't really decided how to name versions.

**Comment by wu-sheng** [comment]
I think more popular way is setting a release version(such as 0.1, 0.2, etc.) like other lib or framework. Even OpenTracing is only a spec, but I think it's good for everyone.  

Like HTTP, J2EE spec, it also uses version name like this. 

Further, by having this version, All language implements can match this version. All users will have a clear view about release api and spec.

@yurishkuro

**Comment by cwe1ss** [comment]
language implementations can't use the same versions if they themselves adhere to SemVer. Let's say the opentracing specification is on 0.2 and my csharp-impl is also on 0.2.0 - which version should I use if I have to introduce a change that's not relevant for the specification but is adding stuff to or is breaking my implementation?! 0.2.1 would not follow SemVer and 0.3.0 / 1.0.0 would no longer match the specification.

I guess this should go into a separate issue if we want to further discuss it.

**Comment by bensigelman** [comment]
See https://github.com/opentracing/specification/issues/2...

**Comment by bensigelman** [comment]
@mabn as for the actual issue at hand: yes, the spec itself needs to be updated. I'll make that change.
