### ISSUE TITLE
Is anyone give me profiles for OpenTracing contributors?

### ISSUE THREAD

**Issue by wu-sheng** [opentracing/opentracing.io#163]
@yurishkuro @adriancole @bensigelman 

I need a simple profile for major OpenTracing contributors. Profile includes name, company.

I will have a small meeting about OpenTracing spec. I need these info to introduce OpenTracing.

**Comment by bensigelman** [comment]
@wu-sheng this is not a complete list (e.g., it's missing you :), but it covers many of the contributors: https://github.com/cncf/toc/blob/master/proposals/opentracing.adoc

**Comment by wu-sheng** [comment]
@bensigelman , I have seen profiles, which I need. Maybe, you can add me to the list? :P

**Comment by bensigelman** [comment]
@wu-sheng that list was just part of a (historical) proposal to add OpenTracing to CNCF – it's not a document that's meant to stay up to date.

**Comment by wu-sheng** [comment]
Thank you for informing.
