### ISSUE TITLE
Broken link on the spec

### ISSUE THREAD

**Issue by rakyll** [opentracing/opentracing.io#172]
> "Inject a SpanContext into a "carrier" object for cross-process propagation. The type of the carrier is either determined through reflection or an explicit format identifier. See the end-to-end propagation example to make this more concrete."

End-to-end propagation example for the injector is giving me 404. The extractor's link to http://opentracing.io/documentation/pages/api/cross-process-tracing#propagation-example works.

http://opentracing.io/documentation/pages/spec.html

**Comment by yurishkuro** [comment]
@rakyll fixed, thanks for reporting
