### ISSUE TITLE
Trailing slash issue: http://opentracing.io/spec/ is 404

### ISSUE THREAD

**Issue by ptone** [opentracing/opentracing.io#176]
http://opentracing.io/spec/ is 404 (as found in code comments)
http://opentracing.io/spec is fine

Would also be nice to add a link to https://github.com/opentracing/specification on that page

**Comment by wu-sheng** [comment]
Can you tell me which codes have these comments? Maybe list them, or give me some samples?

**Comment by bensigelman** [comment]
@ptone agreed entirely about the missing link to github.com/opentracing/specification... I'm hoping to clean stuff up over this holiday break, in fact.

**Comment by bensigelman** [comment]
@ptone PTAL at https://github.com/opentracing/opentracing.io/pull/178 if you have time.

**Comment by tedsuo** [comment]
Closing now that this page has been moved.
