### ISSUE TITLE
PHP Library?

### ISSUE THREAD

**Issue by therealgambo** [opentracing/opentracing.io#191]
I see in your docs (http://opentracing.io/documentation/pages/api/api-implementations.html) that a PHP library is in progress, Any update on this? Is there a git repo that we can follow/contribute to?

**Comment by bhs** [comment]
@missionrulz I know that @beberlei was working on something. If you are motivated, it would not be difficult to get this over the line... esp using OT-Ruby as a rough guide.

**Comment by therealgambo** [comment]
I'm just doing some research at the moment for use in a potential project, If it comes down to it I'll have no issue writing the library. I'm sure some others will benefit from having a PHP library as well.

**Comment by wu-sheng** [comment]
@therealgambo  🎉 🎉 🎉  Glad to have PHP lib.

**Comment by jonahgeorge** [comment]
This can be closed 🎉 

https://github.com/opentracing/opentracing-php

**Comment by yurishkuro** [comment]
✌️
