### ISSUE TITLE
Create a UI page listing known integrations & instrumentation libraries

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#192]
We have "supported frameworks" slide show, but I think it would be even better to have a page that 
 1. lists the same information as plain text, with links to frameworks and a brief blurb
 1. links to various instrumentation libraries like https://github.com/ExpansiveWorlds/instrumentedsql, https://github.com/uber-common/opentracing-python-instrumentation, and probably all repos from opentracing-contrib, so that people would know what exists in the ecosystem. Zipkin does a good job at keeping such a list.

**Comment by wu-sheng** [comment]
Agree. Start with OT-contrib/meta list, only released. And contrib repositories.

We should set a catalog principle. Make the page easy to read.

**Comment by yurishkuro** [comment]
it would be good to have links to slide decks, not just videos.

**Comment by yurishkuro** [comment]
cc @reimertz @pritianka

**Comment by pritianka** [comment]
Hey @reimertz you have all the slide decks from KubeCon. Perhaps you can
link to them as a starting point? and then people can PR their own decks
too.
ᐧ

Priyanka Sharma
Advisor, HeavyBit <http://heavybit.com/>
Head of Marketing & Partnerships, LightStep <http://lightstep.com/>
Co-founder, WakaTime <http://www.wakatime.com/> - Quantify your coding
www.twitter.com/pritianka
650-796-7125

**Comment by Shruti9520** [comment]
Hi, @pritianka @yurishkuro I would like to work on this issue. :-)

Thanks!

**Comment by pritianka** [comment]
Hi @Shruti9520 - that's awesome! I know @tedsuo and @bhs have some ideas around what these pages should look like. Let's start a gitter chatroom to discuss?

**Comment by Shruti9520** [comment]
Sure @pritianka :-)

**Comment by Shruti9520** [comment]
@pritianka @yurishkuro I dropped a message on gitter channel. I would like to know where I could find ` slide decks`? So, the workflow will be like this-
1. I will create a demo template for the UI.
2. Start implementing those.

Thanks!

**Comment by yurishkuro** [comment]
talks & slides are currently here: http://opentracing.io/talks-and-videos/, I think my comment was that when we add a video to that list we should always try to ad a link to the respective slide deck. But that's actually not the point of this issue - this issue is to organize information about integrations / instrumentations, i.e. something like
  * Java
    * Dropwizard
    * Spring-Boot
    * JAXRS
  * Python
    * Flask
    * Django
etc.

**Comment by Shruti9520** [comment]
@yurishkuro Thanks! I'll submit a demo template of the page.

**Comment by tedsuo** [comment]
This is now being addressed via https://github.com/opentracing/opentracing.io/issues/343
