### ISSUE TITLE
The new website is distorted in Safari, MacOS

### ISSUE THREAD

**Issue by wu-sheng** [opentracing/opentracing.io#195]
`GETTING STARTED` began two lines, and have a blank between it and `BLOG`.

<img width="1029" alt="wx20170324-162923 2x" src="https://cloud.githubusercontent.com/assets/5441976/24286244/3aa70f66-10af-11e7-9888-5a05ad587873.png">

**Comment by wu-sheng** [comment]
@reimertz And, I got the 404, when click `GETTING STARTED->FAQ`.  I thought we do not have a FAQ page.

**Comment by reimertz** [comment]
I'm on it asap.

**Comment by wu-sheng** [comment]
@reimertz `FAQ` menu still exists, at document website. I think you miss it. 😊  
Ref http://opentracing.io/documentation/pages/authors-and-contributors.html .

**Comment by reimertz** [comment]
@wu-sheng thanks for noticing. Shoudl be fixed by #198. 🤝
