### ISSUE TITLE
Fonts are looking broken across all browsers

### ISSUE THREAD

**Issue by zihotki** [opentracing/opentracing.io#201]
FF v53, Chrome v58 on Windows, IE 11, Edge 38 - fonts on the site look broken:
![image](https://cloud.githubusercontent.com/assets/114631/25564230/11df1750-2daf-11e7-9ece-4b0f318ab7c5.png)
Notice jumping size of non-capitalized letters. It seems to be an issue with the bariol font. In FF I can see a request to the font `http://opentracing.io/documentation/styles/bariol_regular-webfont.eot` which returns 404. Disabling this font using development tools fixes the problem

**Comment by reimertz** [comment]
Oh noes, those are some sad fonts for sure!

Since I cannot see these issues on my computer, I would love to know your OS so that I can look at this when I wake up tomorrow. 😴

Also, @zihotki, thanks for catching this! 🙏

**Comment by zihotki** [comment]
I'm using Windows 10 Pro x64, tried also with incognito modes in Chrome and FF as well as portable version of FF - the problem is still there

**Comment by bhs** [comment]
@reimertz @zihotki is this resolved?

**Comment by zihotki** [comment]
@bhs no, still see the same behavior - in FF still 404 for http://opentracing.io/documentation/styles/bariol_regular-webfont.eot, and letters are jumpy in all browsers

**Comment by reimertz** [comment]
Thanks for the reminder @bhs, I couldn't reproduce it running Windows on my Mac (using virtual box) so it ended up on my todo-list..

I took another look at this now using [BrowserStack](https://www.browserstack.com) but still cannot reproduce the jumpy letters bug. 🤔

I do see those 404's happening though on certain browsers and it seems to be related to them not fully supporting data uris (`src: url(data:font/woff;....)`), so will investigate and fix that and hope that this will fully fix the jumpy font bug. 🐛

**Comment by zihotki** [comment]
yep, works now!
