### ISSUE TITLE
Add inspectIT to Tracers

### ISSUE THREAD

**Issue by pbouillet** [opentracing/opentracing.io#205]
We released last week our new version of inspectIT (https://github.com/inspectIT/inspectIT / http://inspectit.rocks) with our new tracing approach based completely on opentracing and our javaagent instrumentation. See following resources for more information if interested:

- https://inspectit-performance.atlassian.net/wiki/display/DOC17/opentracing.io+API+implementation
- http://blog.novatec-gmbh.de/inspectit-1-7-cross-jvm-tracing/

In addition to the server-side tracing, we will provide very soon a complete end-to-end tracing approach with an additional JavaScript instrumentation and tracer.

A matching white logo is attached to this issue and the text could look like the following:

> [inspectIT](http://www.inspectit.rocks) aims to be an end-to-end APM solution for Java with support for OpenTracing. The instrumentation capability allows to set up inspectIT in no time with an extensive support for different frameworks and application servers. For more information, take a look at our [documentation](https://inspectit-performance.atlassian.net/wiki/spaces/DOC).

![logo-white](https://cloud.githubusercontent.com/assets/12099231/26341000/c166b4fa-3f91-11e7-94d4-e6ad61ce94a7.png)

We would be very happy if we are listed on your Supported Tracers page.

**Comment by wu-sheng** [comment]
@pbouillet Glad to have new supported tracer. :+1:  Welcome. You can send a pr to add youself on our pagesite.

**Comment by pbouillet** [comment]
@wu-sheng PR #206 is created :smile:

**Comment by wu-sheng** [comment]
#206 has been merged.  Check the website later. : )
