### ISSUE TITLE
the supported tracers list needs maintenance

### ISSUE THREAD

**Issue by adriancole** [opentracing/opentracing.io#216]
https://github.com/opentracing/opentracing.io/blob/master/_data/tracers.yaml seems a bit out-of-date. Seems for a tracer to be supported, it firstly has to be a tracer and secondly be on a supported system.

* https://github.com/sourcegraph/appdash is no longer maintained
* https://github.com/tracer/tracer is also no longer maintained
* http://www.hawkular.org/hawkular-apm/ isn't valid anymore as they no longer have their own tracer, rather re-use jaeger's

The others look fine as they indeed have tracers, are on systems that are still maintained, and are reasonably current.

**Comment by wu-sheng** [comment]
Agreed, if the projects have been changed or no-maintained, they shouldn't be part of list.

**Comment by yurishkuro** [comment]
Interestingly enough, there are APM companies that don't necessarily provide OT-compatible tracers themselves, but they provide integration and/or instrumentation based on OT, for example Kamon and RisingStack.

[Tracelytics](https://github.com/tracelytics/go-traceview/tree/master/v1/tv/ottv) has OT tracer now, can be added to the list  - @cce

**Comment by adriancole** [comment]
I think there are two lists on the front page, but neither get exactly what
you are saying. "Supported Tracers" is a different concept than "I accept a
tracer".

To the degree something implements a Tracer interface is probably the
closest you can reasonably get to being honest with "Supported Tracers".

If you want to broaden it to "integration exists for X" you could, too.
Regardless, paused or dead projects clutter the list and water down the
message.

my 2p and y'all can feel free to keep orphaned projects on the list if it
suits you of course.

**Comment by tedsuo** [comment]
FYI we will be solving this via the new registry page: https://github.com/opentracing/opentracing.io/issues/343
