### ISSUE TITLE
The skywalking.org site (which we link to) has been hacked

### ISSUE THREAD

**Issue by tiffon** [opentracing/opentracing.io#265]
Looks like http://skywalking.org/ has been hacked.

For instance, it just redirected me to: http://www.memevibe.com/2017/05/01/top-10-handsome-men-usa/

We should probably update the link to point refer http://skywalking.apache.org/

**Comment by wu-sheng** [comment]
Yes, agree. We should update the website.

**Comment by wu-sheng** [comment]
PR submitted.

**Comment by wu-sheng** [comment]
Merged and fixed
