### ISSUE TITLE
Getting Started for Developers

### ISSUE THREAD

**Issue by tedsuo** [opentracing/opentracing.io#269]
Audience - Developers who are getting started with writing instrumentation, want to play with the code.  Get up and running quickly.

@jpkrohling:  Katacoda is actually pretty good for this purpose.

* Setting up a development environment
* Hello world example
* Multiple languages: Go, Java, etc
* Easy to start without a lot of installation or requirements
* Step-by-step walkthrough also available as a github repo

**Comment by jpkrohling** [comment]
We have [Yuri's OpenTracing tutorial](https://github.com/yurishkuro/opentracing-tutorial) already as a [Katacoda scenario](https://www.katacoda.com/courses/opentracing). Would that fit the purpose, or do you think a new set of scenarios would be required?
