### ISSUE TITLE
New Site Launch Checklist

### ISSUE THREAD

**Issue by tedsuo** [opentracing/opentracing.io#291]
This issue is to track any final things that need to be fixed or created in order to launch the new site (besides content). Please leave a comment with anything you notice or have questions about, and I'll keep the top level description up to date.

## DropDown menus
* currently match old site.
* can they be dynamic?

## Hosting/Deployment
* https://opentracing.netlify.com/
* can deploys start happening, from the v2.0 branch, to a secondary domain, until the site launches?
* where/how do DNS changes need to be made in order to launch?

**Comment by lucperkins** [comment]
@tedsuo What strikes you as deficient about the dropdown menus on the Hugo version of the site? As far as I can tell they do match the old site, plus a new dropdown ("Specification"). And what do you mean dynamic? Right now they're generated from YAML config files rather than being hard-coded in the layouts.

**Comment by tedsuo** [comment]
Ah, I found the yaml file for the menus, thanks @lucperkins.

I don't have the netlify credentials myself, I'll see about tracking them down (@yurishkuro mentioned he made you an admin btw). I think if we could get https://opentracing.netlify.com/ pointed at the `v2.0` branch, that would be enough for now/

**Comment by jpkrohling** [comment]
I just checked the v2 branch and I'm missing some content, like the [Outreachy page](http://opentracing.io/outreachy) (`/outreachy`) and ["Talks and Videos"](http://opentracing.io/talks-and-videos/). Did I miss a build step?

**Comment by tedsuo** [comment]
@jpkrohling those pages are in an odd place in the current site, they have to be recreated.

**Comment by tedsuo** [comment]
Site's Launched! 🥇
