### ISSUE TITLE
Securing opentracing.io website with HTTPS?

### ISSUE THREAD

**Issue by vszakats** [opentracing/opentracing.io#337]
The website is hosted on GitHub and GitHub supports HTTPS on custom domains:
https://help.github.com/articles/securing-your-github-pages-site-with-https/

Can you enable it for opentracing.io?

**Comment by yurishkuro** [comment]
I think we should keep this open, but it might be easier solved once we migrate to Netlify.

@tedsuo what's the ETA for publishing the new website? What is the blocker?

**Comment by vszakats** [comment]
It seems that HTTPS is working fine now with <https://opentracing.io/>. Thanks guys!

Ref: https://github.com/Homebrew/homebrew-core/pull/32770
