### ISSUE TITLE
Footer bug causes content to move on hover

### ISSUE THREAD

**Issue by heyneff** [opentracing/opentracing.io#341]
![ot-fotter-bug](https://user-images.githubusercontent.com/3827051/46758560-fc449280-cc81-11e8-986a-bd8281918b1a.gif)

**Comment by austinlparker** [comment]
Looking through other usages of that button style, it does seem that it's intended to be a feature... that said, I'm not really in love with it. Looks weird, especially in the footer. What if we added some other affordance to the buttons to make them pop a bit more? Maybe something to look like it's being depressed.
