### ISSUE TITLE
Footer hover states are hard to read

### ISSUE THREAD

**Issue by heyneff** [opentracing/opentracing.io#342]
<img width="280" alt="screen shot 2018-10-10 at 11 03 43 am" src="https://user-images.githubusercontent.com/3827051/46761379-277eb000-cc89-11e8-8a97-dcfade6ffd53.png">

The footer hover state makes the text hard to read. The aim for accessibility is to hit a contrast ratio of at least 4.5 for text this size. The hover state ratio is 1.68. Obviously not a deal-breaker, but something to consider. Does this project have guidelines about accessibility?

See also https://usecontrast.com/guide

**Comment by tedsuo** [comment]
Thanks @heyneff. We're going to do a design overhaul, and will address this as part of that.
