### ISSUE TITLE
Missing Outreachy pages

### ISSUE THREAD

**Issue by jpkrohling** [opentracing/opentracing.io#344]
On the new website, it looks like the Outreachy pages for the previous programs weren't migrated. Old content:

https://github.com/opentracing/opentracing.io/blob/e636583eb3d338807790832c15fcc3ac73e2a767/pages/outreachy-201801.md

https://github.com/opentracing/opentracing.io/blob/e636583eb3d338807790832c15fcc3ac73e2a767/pages/outreachy-201702.md

They are linked here on the new website:
https://github.com/opentracing/opentracing.io/blob/88ea629ab5b7738fb60bc6d1916d0763d3ff8ebf/content/get-involved/outreachy.md#previous-programs

**Comment by tedsuo** [comment]
Added!

**Comment by jpkrohling** [comment]
Looks great, thanks!
