### ISSUE TITLE
incorrect email on conference speaking opportunities page

### ISSUE THREAD

**Issue by irabinovitch** [opentracing/opentracing.io#358]
On https://opentracing.io/get-involved/register/  there is a section called "Conference Speaking Opportunities". 

The email it lists as a contact hello@opentracing.com bounces.  Changing this to hello@opentracing.io also bounces.  Is there another email it should be pointing at?

**Comment by irabinovitch** [comment]
CC @tedsuo

**Comment by austinlparker** [comment]
Seems like it should point at the Google Group's email address - I want to say that's what that address pointed to originally?

**Comment by yurishkuro** [comment]
Yes let's avoid aliases and just point to Google group.
