### ISSUE TITLE
Fix Java Getting Started page

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#418]
https://opentracing.io/docs/getting-started/ provides a Java snippet that uses `com.uber.jaeger.Configuration`, which is deprecated quite a while ago in favor of `io.jaegertracing.*` artifacts.

  * add the dependency (e.g. POM XML) before the Java snippet to that people know what to import (e.g. https://github.com/yurishkuro/opentracing-tutorial/blob/20bdaf592884553e2c1669c36754af1df4ba1c71/java/pom.xml#L24)
  * update snippet to use the current Jaeger class names (e.g. https://github.com/yurishkuro/opentracing-tutorial/blob/20bdaf592884553e2c1669c36754af1df4ba1c71/java/src/main/java/lib/Tracing.java#L27)

**Comment by yurishkuro** [comment]
cc @jpkrohling @austinlparker @tedsuo

**Comment by austinlparker** [comment]
I can take this.
