### ISSUE TITLE
OT is now a CNCF Archived project, update homepage etc

### ISSUE THREAD

**Issue by chalin** [opentracing/opentracing.io#457]
For details, see https://www.cncf.io/blog/2021/08/26/opentelemetry-becomes-a-cncf-incubating-project.

Things to do (at a minimum):

- [ ] Update the CNCF designation at the bottom of the homepage
- [ ] Add a banner (replacing the current one), that might read something like this:
  > OpenTracing is an **[Archived][]** CNCF project. [Learn more][]

We might want to wait to link to **Archived** projects until https://github.com/cncf/toc/pull/710 is merged.

/cc @caniszczyk @austinlparker 

[Archived]: #link-to-cncf-projects
[Learn more]: https://www.cncf.io/blog/2021/08/26/opentelemetry-becomes-a-cncf-incubating-project

**Comment by yurishkuro** [comment]
I think the first item on "things to do at minimum" is to have a clear & well-documented migration path for existing users of OT. It should've been done before calling the TOC vote imo.

**Comment by chalin** [comment]
I believe that there is a migration path -- @tedsuo can comment on that.

Unfortunately, I see that it isn't mentioned in the [blog](https://www.cncf.io/blog/2021/08/26/opentelemetry-becomes-a-cncf-incubating-project). We will want users to have access to that information.
