### ISSUE TITLE
get trivial code examples front-and-center on opentracing.io

### ISSUE THREAD

**Issue by bensigelman** [opentracing/opentracing.io#65]
I was talking about OpenTracing with a friendly engineer this afternoon and he took a look at the site... He immediately went searching for code samples and came upon some of the slightly more elaborate ones before he found the slightly simpler ones.

We should make sure the first code that people see is more of the "hello world" variety than the "tricky request-handling extraction with tags" variety :)

Filing this issue so we don't forget.

**Comment by yurishkuro** [comment]
strictly speaking, the very first example on the use-cases is the simplest, tracing a function. The next one though, function2, uses the old syntax, so we have some clean-up to do.

It also feels the site might use some reorg. For example, Stepping Back section in the use-cases might look much better closer to the home page. But there are many ways to

**Comment by bensigelman** [comment]
I agree about the site reorg. By "front and center" I mean "when you go to opentracing.io and before you click on anything".

**Comment by yurishkuro** [comment]
Agreed, we should add something to the home page, similar to https://developers.google.com/protocol-buffers/
