### ISSUE TITLE
Running multiple tracing implementations simultaneously

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#66]
This question has come up a few times, so I want to record it here as a possible future extension.

@wladekb on [gitter](https://gitter.im/opentracing/public?at=56c73c2dddb992576753b546) said:

> 1. How would I approach plugging in two different implementations, say I want Zipkin-compatible one and another new one I want to test but don't want to break data flow to Zipkin?

The possible solution to this is a composite dispatching tracer that implements OpenTracing API and delegates all API calls to one or more underlying implementations. E.g.

``` python
class CompositeTracer(opentracing.Tracer):
    def __init__(self, *tracers):
        self._tracers = tracers

    def start_span(self,
                   operation_name=None,
                   parent=None,
                   tags=None,
                   start_time=None):
        spans = []
        for tracer in self._tracers:
            span = tracer.start_span(operation_name, parent, tags, start_time)
            spans.append(span)
        return CompositeSpan(spans)
```

**Comment by bensigelman** [comment]
Yeah, this is something I had a TODO about in one of the early headers. Most of it is easy and clean to build, though the trace_attributes piece feels potentially wasteful (storing them N times) and also problematic since we don't know which getter to delegate to.

**Comment by yurishkuro** [comment]
yes, the attributes is the only read operation in the whole API, so I think the composite tracer will have to pick one of the delegates, i.e. always the first, and the end users can configure delegate tracers in the proper order.

**Comment by bensigelman** [comment]
just thinking out loud, but I can also imagine a design where the composite tracer:
- handles the attributes natively
  - ... though also delegates the setter calls just so the nested tracers have access to them
- uses the Split injector on each nested tracer *and discards the (duplicated) attribute portion*
- and encodes the attributes exactly once on its own

This means we would have 1 copy of the attributes going over the wire along with the N tracer states. More work/complexity, though.

**Comment by yurishkuro** [comment]
> More work/complexity, though.

Yes, and I am not sure what it gains us. I consider this whole use case as more of a temporary situation in any system, like "let me test another tracer". If this is something that people want to run permanently in production, then additional tricks on de-duping the headers may come (hopefully based on contributions from those people :smiling_imp: ).

**Comment by bensigelman** [comment]
FWIW, I think running two

**Comment by bensigelman** [comment]
(sorry about that noise ^^^)

**Comment by bensigelman** [comment]
... continued at https://github.com/opentracing/specification/issues/9
