### ISSUE TITLE
Consolidate common tags definition and auto-generate language bindings

### ISSUE THREAD

**Issue by yurishkuro** [opentracing/opentracing.io#76]
Pulled out of https://github.com/opentracing/opentracing.github.io/pull/61

I think long term it would be great to have a yaml file in the docs repo that defines each tag (name, description, value type), then symlink the docs repo into each language repo as a git submodule, and write simple code generators. That way we would achieve uniform descriptions of the tags, make sure that each std tag is defined in each langauge, etc. The actual html doc can also be generated from the same yaml file.  All the generators can probably be written once using the same template framework.

**Comment by bensigelman** [comment]
+1 -- great idea.

**Comment by bensigelman** [comment]
(c.f. #92)

**Comment by bensigelman** [comment]
... continued at https://github.com/opentracing/specification/issues/10
